[2024-08-17T00:33:21.859+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T00:33:21.870+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_values_TS_11.get_cases_dataset.predict_data scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T00:33:21.875+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_values_TS_11.get_cases_dataset.predict_data scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T00:33:21.875+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-17T00:33:21.885+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_cases_dataset.predict_data> on 2024-08-04 00:00:00+00:00
[2024-08-17T00:33:21.893+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=22469) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T00:33:21.894+0000] {standard_task_runner.py:63} INFO - Started process 22540 to run task
[2024-08-17T00:33:21.894+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'predict_values_TS_11', 'get_cases_dataset.predict_data', 'scheduled__2024-08-04T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpgb6mtoot']
[2024-08-17T00:33:21.896+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask get_cases_dataset.predict_data
[2024-08-17T00:33:21.929+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_values_TS_11.get_cases_dataset.predict_data scheduled__2024-08-04T00:00:00+00:00 [running]> on host 08898c2f83c5
[2024-08-17T00:33:21.990+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ruslan Solarev' AIRFLOW_CTX_DAG_ID='predict_values_TS_11' AIRFLOW_CTX_TASK_ID='get_cases_dataset.predict_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T00:00:00+00:00'
[2024-08-17T00:33:21.991+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T00:33:22.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T00:33:22.016+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks_2/predict_data.py", line 71, in predict_data
    dates = dataset.index.tolist() +  get_dates(dataset, pred_days).tolist()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks_2/predict_data.py", line 16, in get_dates
    end_date = begin_date + timedelta(days=length)
               ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "datetime.timedelta") to str
[2024-08-17T00:33:22.024+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=predict_values_TS_11, task_id=get_cases_dataset.predict_data, run_id=scheduled__2024-08-04T00:00:00+00:00, execution_date=20240804T000000, start_date=20240817T003321, end_date=20240817T003322
[2024-08-17T00:33:22.032+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 42 for task get_cases_dataset.predict_data (can only concatenate str (not "datetime.timedelta") to str; 22540)
[2024-08-17T00:33:22.068+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-17T00:33:22.084+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-17T00:33:22.088+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
