[2024-08-17T12:29:25.507+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T12:29:25.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_values_TS_26.get_cases_dataset.insert_data_to_db scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T12:29:25.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_values_TS_26.get_cases_dataset.insert_data_to_db scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T12:29:25.528+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-17T12:29:25.539+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): get_cases_dataset.insert_data_to_db> on 2024-08-04 00:00:00+00:00
[2024-08-17T12:29:25.553+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=39805) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T12:29:25.554+0000] {standard_task_runner.py:63} INFO - Started process 41798 to run task
[2024-08-17T12:29:25.554+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'predict_values_TS_26', 'get_cases_dataset.insert_data_to_db', 'scheduled__2024-08-04T00:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpj8rjx7se']
[2024-08-17T12:29:25.556+0000] {standard_task_runner.py:91} INFO - Job 170: Subtask get_cases_dataset.insert_data_to_db
[2024-08-17T12:29:25.595+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_values_TS_26.get_cases_dataset.insert_data_to_db scheduled__2024-08-04T00:00:00+00:00 [running]> on host 57503ef29846
[2024-08-17T12:29:25.659+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ruslan Solarev' AIRFLOW_CTX_DAG_ID='predict_values_TS_26' AIRFLOW_CTX_TASK_ID='get_cases_dataset.insert_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T00:00:00+00:00'
[2024-08-17T12:29:25.660+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T12:29:25.670+0000] {sql.py:276} INFO - Executing: None
[2024-08-17T12:29:25.678+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-08-17T12:29:25.681+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T12:29:25.681+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-08-17T12:29:25.689+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=predict_values_TS_26, task_id=get_cases_dataset.insert_data_to_db, run_id=scheduled__2024-08-04T00:00:00+00:00, execution_date=20240804T000000, start_date=20240817T122925, end_date=20240817T122925
[2024-08-17T12:29:25.704+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 170 for task get_cases_dataset.insert_data_to_db (List of SQL statements is empty; 41798)
[2024-08-17T12:29:25.728+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-17T12:29:25.744+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-17T12:29:25.747+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
