[2024-08-16T05:04:43.052+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T05:04:43.064+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_values_TS_1.get_datasets_from_google scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-16T05:04:43.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_values_TS_1.get_datasets_from_google scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-16T05:04:43.069+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-16T05:04:43.078+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_datasets_from_google> on 2024-08-04 00:00:00+00:00
[2024-08-16T05:04:43.082+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=199) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T05:04:43.082+0000] {standard_task_runner.py:63} INFO - Started process 201 to run task
[2024-08-16T05:04:43.082+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'predict_values_TS_1', 'get_datasets_from_google', 'scheduled__2024-08-04T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpdvvkc8nl']
[2024-08-16T05:04:43.084+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask get_datasets_from_google
[2024-08-16T05:04:43.117+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_values_TS_1.get_datasets_from_google scheduled__2024-08-04T00:00:00+00:00 [running]> on host 67cef99b955e
[2024-08-16T05:04:43.165+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ruslan Solarev' AIRFLOW_CTX_DAG_ID='predict_values_TS_1' AIRFLOW_CTX_TASK_ID='get_datasets_from_google' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T00:00:00+00:00'
[2024-08-16T05:04:43.166+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T05:04:43.184+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T05:04:43.185+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_data() missing 1 required positional argument: 'path'
[2024-08-16T05:04:43.191+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=predict_values_TS_1, task_id=get_datasets_from_google, run_id=scheduled__2024-08-04T00:00:00+00:00, execution_date=20240804T000000, start_date=20240816T050443, end_date=20240816T050443
[2024-08-16T05:04:43.199+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task get_datasets_from_google (get_data() missing 1 required positional argument: 'path'; 201)
[2024-08-16T05:04:43.216+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-16T05:04:43.226+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-16T05:04:43.229+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
