[2024-08-17T10:27:43.442+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T10:27:43.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_values_TS_20.get_cases_dataset.create_movies_table scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T10:27:43.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_values_TS_20.get_cases_dataset.create_movies_table scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T10:27:43.459+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-17T10:27:43.470+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): get_cases_dataset.create_movies_table> on 2024-08-04 00:00:00+00:00
[2024-08-17T10:27:43.477+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=97204) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T10:27:43.478+0000] {standard_task_runner.py:63} INFO - Started process 97822 to run task
[2024-08-17T10:27:43.479+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'predict_values_TS_20', 'get_cases_dataset.create_movies_table', 'scheduled__2024-08-04T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpbvudm283']
[2024-08-17T10:27:43.480+0000] {standard_task_runner.py:91} INFO - Job 112: Subtask get_cases_dataset.create_movies_table
[2024-08-17T10:27:43.513+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_values_TS_20.get_cases_dataset.create_movies_table scheduled__2024-08-04T00:00:00+00:00 [running]> on host 57503ef29846
[2024-08-17T10:27:43.569+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ruslan Solarev' AIRFLOW_CTX_DAG_ID='predict_values_TS_20' AIRFLOW_CTX_TASK_ID='get_cases_dataset.create_movies_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T00:00:00+00:00'
[2024-08-17T10:27:43.570+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T10:27:43.577+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS Morbidity (
            id SERIAL PRIMARY KEY,
            Date DATETIME,
            Country VARCHAR
            Cases FLOAT
            is_Pred BOOLEAN
        )
[2024-08-17T10:27:43.583+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-08-17T10:27:43.591+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-08-17T10:27:43.591+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T10:27:43.592+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 411, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "http://host.docker.internal" to address: Name or service not known

[2024-08-17T10:27:43.598+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=predict_values_TS_20, task_id=get_cases_dataset.create_movies_table, run_id=scheduled__2024-08-04T00:00:00+00:00, execution_date=20240804T000000, start_date=20240817T102743, end_date=20240817T102743
[2024-08-17T10:27:43.607+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 112 for task get_cases_dataset.create_movies_table (could not translate host name "http://host.docker.internal" to address: Name or service not known
; 97822)
[2024-08-17T10:27:43.651+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-17T10:27:43.659+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-17T10:27:43.669+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-17T10:27:43.673+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
